feat(LINGUIST-28): Initialized Spring, implemented security, created login and register endpoints
LinguistAI/Linguist-AI-MVP pull request #4
Opened 2023-10-21 16:05 UTC by elif-krvan

2023-10-21 16:29 UTC, can-aslan submitted a review, later dismissed

2023-10-21 21:05 UTC, tolgaozgun requested changes
Should we use environment variables to application.properties, we can use Github and .env files to manage environment varibles. As the repo is public, our db will be vulnerable to attacks.

2023-10-22 08:15 UTC, elif-krvan commented
> Should we use environment variables to application.properties, we can use Github and .env files to manage environment varibles. As the repo is public, our db will be vulnerable to attacks.

Spring automatically uses the variables in the application.properties. Therefore, it would be better to include it in the gitignore file.

2023-10-22 09:07 UTC, can-aslan approved these changes

2023-10-22 09:21 UTC, merged